name: VPS SSHX + PufferPanel + Ngrok

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Executa todo início de hora
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  root_apolinario:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Inicia VPS temporária via SSHX
      - name: Iniciando VPS temporária (sshx.io)
        run: curl -sSf https://sshx.io/get | sh -s run &

      # Manter job ativo (24/7 temporário) 
      - name: Manter job ativo 
        run: tail -f /dev/null
